# Render.com 部署配置 - 完整版Flask应用
services:
- type: web
  name: umami-csv-import
  env: python
  plan: free
  buildCommand: pip install -r requirements_full.txt
  startCommand: gunicorn app:app
  envVars:
  - key: FLASK_ENV
    value: production
  - key: FLASK_SECRET_KEY
    generateValue: true
  - key: PYTHON_VERSION
    value: 3.9.18
